name: Jacoco

# workflow triggers
on:
  # manually
  workflow_dispatch:
  workflow_call:
  # PRs on `main`
  pull_request:
    #branches:
    #- main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      # setup Java and cache Maven dependencies
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'

      # run Maven build
      - name: Maven Build
        #run: ./mvn --batch-mode --update-snapshots verify
        run: mvn clean org.jacoco:jacoco-maven-plugin:0.8.8:prepare-agent verify org.jacoco:jacoco-maven-plugin:0.8.9:report-aggregate
      
      - name: Test moving jacoco reports
        run:  rm -rf target/ && mkdir maintarget && cp -r report/target/* maintarget/
        #run:  rm -rf target/ && mkdir maintarget && cp -r report/target/* maintarget/

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/jacoco-reports/jacoco.xml
          #${{ github.workspace }}/maintarget/jacoco-reports/jacoco.xml
          #${{ github.workspace }}/**/report/target/jacoco-reports/jacoco.xml
          #${{ github.workspace }}/**/jacoco.xml
          #${{ github.workspace }}/**/report/target/jacoco-reports/index.xml
          #paths: |
           # ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            #${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          #token: ${{ secrets.github_token }}
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          #debug-mode: true

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      
      - name: Stage Build Results
        #run: mkdir staging && cp -r `ls -A | grep -v "staging"` staging/
        #run: mkdir staging && cp -r target/ staging/
        run: mkdir staging && cp -r ${{ github.workspace }}/**/target/jacoco-reports/* staging/
        #run: mkdir staging && cp ${{ github.workspace }}/maintarget/target/jacoco-reports/jacoco.xml staging/

       #upload staged packages
      - name: Upload Build Results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Build Results
          path: staging/